let filmer = [
    { navn: "American psycho", 
      regissør: "Mary Harron",
      sett:(true) },
    { navn: "Pelle Politibil", 
      regissør: "Thomas Kaiser",
      sett:(true) },
    { navn: "Smokey & the Bandit", 
      regissør: "Hal Needham",
      sett:(true) },
    { navn: "Blues Brothers", 
      regissør: "John Landis.",
      sett:(true) },
    { navn: "Zoolander", 
      regissør: "Ben Stiller",
      sett:(true) },
    { navn: "Fight club", 
     regissør: "",
     sett:(false) },
    { navn: "Band of Brothers", 
     regissør: "",
     sett:(false) },
    { navn: "", 
     regissør: "",
     sett:(false) },
    { navn: "", 
     regissør: "",
     sett:(false) },
    { navn: "", 
     regissør: "",
     sett:(false) },
  ];    
